/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_VipsThreadpool */

#ifndef _Included_com_criteo_vips_VipsThreadpool
#define _Included_com_criteo_vips_VipsThreadpool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_VipsThreadpool
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsThreadpool_set
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_criteo_vips_VipsThreadpool
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsThreadpool_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
