/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_VipsInit */

#ifndef _Included_com_criteo_vips_VipsInit
#define _Included_com_criteo_vips_VipsInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    getArgv0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_criteo_vips_VipsInit_getArgv0
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsInit_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    checkInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsInit_checkInit
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    threadShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsInit_threadShutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsInit_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    guessPrefix
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_criteo_vips_VipsInit_guessPrefix
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    guessLibdir
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_criteo_vips_VipsInit_guessLibdir
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    versionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_criteo_vips_VipsInit_versionString
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    version
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsInit_version
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_criteo_vips_VipsInit
 * Method:    leakSet
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsInit_leakSet
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
