/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_VipsContext */

#ifndef _Included_com_criteo_vips_VipsContext
#define _Included_com_criteo_vips_VipsContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    setConcurrency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsContext_setConcurrency
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_criteo_vips_VipsContext
 * Method:    getConcurrency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsContext_getConcurrency
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
